language: node_js
node_js:
  - "0.10"

before_install:
  - "export BROWSERS=Firefox"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - npm run cover-publish
addons:
  code_climate:
    repo_token:
      # # get your token from https://codeclimate.com/github/benjamine/frame-channels
      # gem install travis
      # travis encrypt <projecttoken>
      secure: "dt7zkd2W6MVF1L3VIzAmRsV7+qXVEYi57CypSRIbX//6W2Ar5ygnzJaZ8cNSOmSGvVkKvF5y7ubP7Z9QDWaZh3jTunvBSqZabf1Qo9wvia58Ojj5oWbIQAWvAZJAt43moRBxTahLocvPsQtcS3VJgTdjvAGRqHQTLri6Upi9lDk="
